# qutebrowser shortcuts
config.bind(';d', 'set downloads.location.directory ~/Documents ;; hint links download')
config.bind(';D', 'set downloads.location.directory ~/Documents/MyDocuments ;; hint links download')
config.bind(';C', 'set downloads.location.directory ~/Documents/MyDocuments/Client ;; hint links download')
config.bind(';nid', 'set downloads.location.directory ~/Documents/MyDocuments/NID ;; hint links download')
config.bind(';w', 'set downloads.location.directory ~/Downloads ;; hint links download')
config.bind(';m', 'set downloads.location.directory ~/Music ;; hint links download')
config.bind(';p', 'set downloads.location.directory ~/Pictures ;; hint links download')
config.bind(';v', 'set downloads.location.directory ~/Videos ;; hint links download')
config.bind(';s', 'set downloads.location.directory ~/.scripts ;; hint links download')
config.bind(';c', 'set downloads.location.directory ~/.config ;; hint links download')
config.bind(';N', 'set downloads.location.directory /mnt/www/nginx/notes ;; hint links download')
config.bind(';M', 'set downloads.location.directory /mnt ;; hint links download')
config.bind(';bs', 'set downloads.location.directory /home/notami/Documents/MyDocuments/Client/DBS/dbsaurer.com/BU-DBS ;; hint links download')
config.bind(';lg', 'set downloads.location.directory /home/notami/Documents/MyDocuments/Client/LegacyIII/legacythree.org/BU-L3 ;; hint links download')
config.bind(';mh', 'set downloads.location.directory /home/notami/Documents/MyDocuments/Client/MiraclesHappen/miraclesupholstery.com/BU-MH ;; hint links download')
config.bind(';ol', 'set downloads.location.directory /home/notami/Documents/MyDocuments/Client/One ;; hint links download')
config.bind(';us', 'set downloads.location.directory /usr/share ;; hint links download')
