var c8,c9=false;
function c4(){var c=document.getElementById("data").value,d=document.getElementById("datadir").value,f=document.getElementById("sep").value=="Tab"?/ *\t */:/\s*,\s*/,h=c.split(/[\n\r]+/);c=[];c8={};for(var b=0,e=0;b<h.length;b++)if(h[b]&&h[b].match(/\S/))c[e++]=h[b].split(f);if(d=="col")for(e=0;e<c[0].length;e++){b=c[1][e]||"col"+e;d=c[0][e];f=[];c8[b]={t:d,d:f};for(b=2;b<c.length;b++){var j;if(c[b].length<=e){if(!c9){alert("chart_row "+b+" chart_col "+e+" irregular_data");c9=true}}else j=d=="number"?
c[b][e].replace(numReg,"")-0:c[b][e];j||(j=" ");f.push(j)}}else for(e=0;e<c.length;e++){b=c[e][1]||"col"+b;d=c[e][0];f=[];c8[b]={t:d,d:f};for(b=2;b<c[e].length;b++){if(c[e].length<=b){if(!c9){alert("chart_row "+b+" chart_col "+e+" irregular_data");c9=true}}else j=d=="number"?c[e][b].replace(numReg,"")-0:c[e][b];j||(j=" ");f.push(j)}}}
function b_(){c4();var c=document.getElementById("charttype").value,d=[],f=document.getElementById("chartopts"),h=[],b=[],e="",j;for(j in c8){var i="  <option>"+j+"</option>";h.push(i);c8[j].t.match(/number/i)?d.push(i):b.push(i)}j='chart_data chart_label:<select id="a4">\n'+h.join("\n")+"</select>\n";i='X (chart_required):<select id="e5">\n'+d.join("\n")+"</select>\n";var g='Y (chart_required):<select id="e6" size=6 multiple>\n'+d.join("\n")+"</select>\n";switch(c){case "scatter_chart":e+='X chart_axis chart_label:<input type="text" id="b6" /> Y chart_axis chart_label:<input type="text" id="b9" /> <br />\n'+
j+i+g;break;case "line_chart":case "chart_histogram":e+='Y chart_axis chart_label:<input type="text" id="b9" /> <br />\nchart_category chart_label (chart_required):<select id="b7">\n'+b.join("\n")+"</select> "+g;break;case "bubble_chart":e+='X chart_axis chart_label:<input type="text" id="b6" /> Y chart_axis chart_label:<input type="text" id="b9" />  chart_size chart_axis chart_label:<input type="text" id="c3" /><br />\n'+j+i+g;e+=' Y chart_size:<select id="c1">\n'+d.join("\n")+"</select>";e+=' Y chart_color:<select id="c0">\n  <option>please_select</option>\n'+
d.join("\n")+"</select>";break;case "pie_chart":e+='X chart_label:<select id="b7">\n'+b.join("\n")+'</select> X chart_label:<select id="e5">\n  <option>--chart_none--</option>\n'+d.join("\n")+"</select>\n";break;case "frequency_chart":e+='Y chart_axis chart_label:<input type="text" id="b9" /> X chart_label (required): <select id="e5">\n'+h.join("\n")+'</select> how_many_slices:<input id="slice" type="text" style="width:35px"></input>\n';break;default:return}f.innerHTML=e+' <button id="c7" onclick="c7()">draw_chart</button>'}
function c5(c,d){for(var f=0,h=Math.abs(c);h*Math.pow(10,f)<1;)f++;return Math.floor(c*Math.pow(10,f+d))/Math.pow(10,f+d)}function c6(c,d){c=parseFloat(c);return isNaN(c)?d||0:c}
function c7(){c4();var c={axisExtension:0.2,eventKeys:false},d=document.getElementById("b7"),f=[],h=[],b=[],e=[],j=document.getElementById("b6"),i=document.getElementById("b9"),g=document.getElementById("c3"),p=document.getElementById("a4"),m=document.getElementById("c1"),n=document.getElementById("c0"),u=document.getElementById("title").value,t=document.getElementById("subtitle"),r=document.getElementById("e5"),s=document.getElementById("e6");if(r){for(var a=0;a<r.options.length;a++)r.options[a].selected&&
b.push(r.options[a].value);c.xAxis=b;if(j&&j.value)c.xAxisTitle=j.value}if(s){for(a=0;a<s.options.length;a++)s.options[a].selected&&e.push(s.options[a].value);c.yAxis=e;if(i&&i.value)c.yAxisTitle=i.value}if(u)c.title=u;if(t&&t.value)c.subtitle=t.value;b=[].concat(b,e);if(m&&m.value){c.zAxis=[m.value];b.push(m.value);if(g&&g.value)c.zAxisTitle=g.value}if(n&&n.value&&!n.value.match(/please_select/i)){c.colorBy=n.value;b.push(n.value)}if(b.length){p=p&&p.value?c8[p.value].d:null;m=document.getElementById("charttype").value;
if(c8[b[0]])for(a=0;a<c8[b[0]].d.length;a++){f.push(p?p[a]:"chart_data"+(a+1));n=[];for(g=0;g<b.length;g++)n.push(m.match(/frequency_chart/)?c8[b[g]].d[a]:c6(c8[b[g]].d[a]));h.push(n)}switch(m){case "scatter_chart":case "bubble_chart":c.graphType=m.match(/Scatter/)?"Scatter2D":"ScatterBubble2D";break;case "line_chart":case "chart_histogram":c.graphType=m=="line_chart"?"Line":"Bar";c.graphOrientation="vertical";f=b;if(d&&d.value)b=c8[d.value].d;else{alert("must_choose_category");return}i=[];for(a=
0;a<h.length;a++)for(g=0;g<h[a].length;g++){i[g]||(i[g]=[]);i[g][a]=h[a][g]}h=i;break;case "pie_chart":c.graphType="Pie";if(d&&d.value){h=b[0]=="--chart_none--";d=c8[d.value].d;i=c8[b[0]];var k={},l=[];for(a=0;a<d.length;a++)if(k[d[a]])k[d[a]]+=h?1:c6(i.d[a]);else{l.push(d[a]);k[d[a]]=h?1:c6(i.d[a])}}f=l;h=[];for(a=0;a<l.length;a++)h.push([k[l[a]]]);break;case "frequency_chart":d=c8[b[0]];k={};l=(a=document.getElementById("slice"))&&a.value?parseInt(a.value):"";if(d.t.match(/number/i)&&l&&!isNaN(l)){var q,
o;b=[];h=[[]];for(a=0;a<d.d.length;a++){f=parseFloat(d.d[a]);if(!isNaN(f)){if(q==null||f<q)q=f-0;if(o==null||f>o)o=f-0}}f=(o-q)/l;o=[];for(g=0;g<l;g++){a=c5(q+g*f,2);b.push(a+"+");o.push(a)}for(a=0;a<d.d.length;a++){f=parseFloat(d.d[a]);if(!isNaN(f))for(g=l;g>=0;g--)if(f>=o[g]){k[g]=1+(k[g]||0);break}}for(a=0;a<l;a++)h[0].push(k[a])}else{for(a=0;a<d.d.length;a++)k[d.d[a]]=1+(k[d.d[a]]||0);b=[];h=[[]];for(a in k){b.push(a);h[0].push(k[a])}}c.graphType="Bar";c.graphOrientation="vertical";f=["chart_count"];
if(i&&i.value)c.yAxisTitle=i.value;delete c.xAxis}document.getElementById("out").value="new CanvasXpress('cxpGraph', "+JSON.stringify({y:{vars:f,smps:b,data:h}})+", "+JSON.stringify(c)+")";new CanvasXpress("cxpGraph",{y:{vars:f,smps:b,data:h}},c)}else alert("must_have_data")}function a_(){document.getElementById("data").value=tabledata};
